// Generated by CoffeeScript 1.9.1
(function() {___jdce_logger("/js/controllers/todos.js", 0);
  var bind = function(){___jdce_logger("/js/controllers/todos.js", 1);},
    extend = function(child, parent) {___jdce_logger("/js/controllers/todos.js", 2); for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() {___jdce_logger("/js/controllers/todos.js", 3); this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.Todos = (function(superClass) {___jdce_logger("/js/controllers/todos.js", 4);
    var ENTER_KEY, ESCAPE_KEY, TPL;

    extend(Todos, superClass);

    ENTER_KEY = 13;

    ESCAPE_KEY = 27;

    TPL = Handlebars.compile($('#todo-template').html());

    Todos.prototype.elements = {
      '.edit': 'editElem'
    };

    Todos.prototype.events = {
      'click    .destroy': 'remove',
      'click    .toggle': 'toggleStatus',
      'dblclick label': 'edit',
      'keydown  .edit': 'revertEditOnEscape',
      'keyup    .edit': 'finishEditOnEnter',
      'blur     .edit': 'finishEdit'
    };

    function Todos(){___jdce_logger("/js/controllers/todos.js", 5);}

    Todos.prototype.render = function(){___jdce_logger("/js/controllers/todos.js", 6);};

    Todos.prototype.remove = function(){___jdce_logger("/js/controllers/todos.js", 7);};

    Todos.prototype.toggleStatus = function(){___jdce_logger("/js/controllers/todos.js", 8);};

    Todos.prototype.edit = function(){___jdce_logger("/js/controllers/todos.js", 9);};

    Todos.prototype.finishEdit = function(){___jdce_logger("/js/controllers/todos.js", 10);};

    Todos.prototype.finishEditOnEnter = function(){___jdce_logger("/js/controllers/todos.js", 11);};

    Todos.prototype.revertEdit = function(){___jdce_logger("/js/controllers/todos.js", 12);};

    Todos.prototype.revertEditOnEscape = function(){___jdce_logger("/js/controllers/todos.js", 13);};

    return Todos;

  })(Spine.Controller);

}).call(this);
