// Generated by CoffeeScript 1.6.3
(function() {___jdce_logger("/js/app.js", 0);
  var App, AppController, Todo, TodoController, app, router, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) {___jdce_logger("/js/app.js", 1); for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() {___jdce_logger("/js/app.js", 2); this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Todo = (function(_super) {___jdce_logger("/js/app.js", 3);
    __extends(Todo, _super);

    function Todo(){___jdce_logger("/js/app.js", 4);}

    Todo.belongsTo('app', {
      inverseOf: 'all',
      as: function(){___jdce_logger("/js/app.js", 5);}
    });

    Todo.property('title', {
      serialize: true
    });

    Todo.property('completed', {
      serialize: true
    });

    Todo.property('incomplete', {
      get: function(){___jdce_logger("/js/app.js", 6);}
    });

    Todo.property('edit');

    Todo.prototype.remove = function(){___jdce_logger("/js/app.js", 7);};

    return Todo;

  })(Serenade.Model);

  App = (function(_super) {___jdce_logger("/js/app.js", 8);
    __extends(App, _super);

    function App() {___jdce_logger("/js/app.js", 9);
      _ref1 = App.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    App.hasMany('all', {
      inverseOf: 'app',
      serialize: true,
      as: function(){___jdce_logger("/js/app.js", 10);}
    });

    App.selection('active', {
      from: 'all',
      filter: 'incomplete'
    });

    App.selection('completed', {
      from: 'all',
      filter: 'completed'
    });

    App.property('label', {
      get: function(){___jdce_logger("/js/app.js", 11);}
    });

    App.property('allCompleted', {
      get: function(){___jdce_logger("/js/app.js", 12);},
      set: function(){___jdce_logger("/js/app.js", 13);}
    });

    App.property('newTitle');

    App.property('filter', {
      value: 'all'
    });

    App.property('filtered', {
      get: function(){___jdce_logger("/js/app.js", 14);}
    });

    App.property('filterAll', {
      get: function(){___jdce_logger("/js/app.js", 15);}
    });

    App.property('filterActive', {
      get: function(){___jdce_logger("/js/app.js", 16);}
    });

    App.property('filterCompleted', {
      get: function(){___jdce_logger("/js/app.js", 17);}
    });

    return App;

  })(Serenade.Model);

  AppController = (function() {___jdce_logger("/js/app.js", 18);
    function AppController(app) {___jdce_logger("/js/app.js", 19);
      this.app = app;
    }

    AppController.prototype.newTodo = function(){___jdce_logger("/js/app.js", 20);};

    AppController.prototype.clearCompleted = function(){___jdce_logger("/js/app.js", 21);};

    return AppController;

  })();

  TodoController = (function() {___jdce_logger("/js/app.js", 22);
    function TodoController(){___jdce_logger("/js/app.js", 23);}

    TodoController.prototype.removeTodo = function(){___jdce_logger("/js/app.js", 24);};

    TodoController.prototype.edit = function(){___jdce_logger("/js/app.js", 25);};

    TodoController.prototype.edited = function(){___jdce_logger("/js/app.js", 26);};

    TodoController.prototype.loadField = function(){___jdce_logger("/js/app.js", 27);};

    return TodoController;

  })();

  app = new App(JSON.parse(localStorage.getItem('todos-serenade')));

  app.changed.bind(function(){___jdce_logger("/js/app.js", 28);});

  router = Router({
    '/': function(){___jdce_logger("/js/app.js", 29);},
    '/active': function(){___jdce_logger("/js/app.js", 30);},
    '/completed': function(){___jdce_logger("/js/app.js", 31);}
  });

  router.init();

  Serenade.view('app', document.getElementById('app').innerHTML);

  Serenade.view('todo', document.getElementById('todo').innerHTML);

  Serenade.controller('app', AppController);

  Serenade.controller('todo', TodoController);

  document.body.insertBefore(Serenade.render('app', app), document.body.children[0]);

}).call(this);
